using System;
using System.Collections.Generic;
using System.IO;

namespace Tund10.Avalonia;

public static class LanguageManager
{
    private static string _currentLanguage = "EE";
    private static readonly string _settingsPath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "AutoApp_Language.txt");

    public static Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["EE"] = new()
        {
            ["Title"] = "Auto Register",
            ["Login"] = "Logi sisse",
            ["Username"] = "Kasutajanimi",
            ["Password"] = "Parool",
            ["Search"] = "Otsi...",
            ["Owners"] = "OMANIKUD",
            ["Cars"] = "AUTOD",
            ["ServicesLogs"] = "TEENUSED & LOGID",
            ["ID"] = "ID",
            ["Name"] = "Nimi",
            ["Phone"] = "Telefon",
            ["Actions"] = "Tegevus",
            ["AddCar"] = "Lisa auto",
            ["Update"] = "Uuenda",
            ["Delete"] = "Kustuta",
            ["Add"] = "Lisa",
            ["Brand"] = "Bränd",
            ["Model"] = "Mudel",
            ["RegNumber"] = "Reg Number",
            ["Owner"] = "Omanik",
            ["AddService"] = "Lisa teenus",
            ["ServiceName"] = "Teenus Nimi",
            ["Price"] = "Hind",
            ["Car"] = "Auto",
            ["Service"] = "Teenus",
            ["Date"] = "Kuupäev",
            ["Mileage"] = "Kilomeetrid",
            ["Save"] = "Salvesta",
            ["Cancel"] = "Tühista",
            ["Message"] = "Sõnum",
            ["OK"] = "OK",
            ["Welcome"] = "Tere tulemast, {0}!",
            ["WrongCredentials"] = "Vale kasutajanimi või parool!",
            ["FillAllFields"] = "Palun täitke kõik väljad.",
            ["CarExists"] = "Sellise registreerimisnumbriga auto on juba olemas.",
            ["CarAdded"] = "Auto lisati edukalt!",
            ["OwnerExists"] = "See omanik on juba olemas.",
            ["OwnerAdded"] = "Omanik lisati edukalt!",
            ["OwnerUpdated"] = "Omanik uuendati edukalt!",
            ["OwnerDeleted"] = "Omanik on edukalt kustutatud.",
            ["CannotDeleteOwner"] = "Seda omanikku ei saa kustutada. Eemalda esmalt seotud autod.",
            ["CarUpdated"] = "Auto uuendati edukalt!",
            ["CarDeleted"] = "Auto on edukalt kustutatud!",
            ["CannotDeleteCar"] = "Seda autot ei saa kustutada. Kustuta esmalt teeninduslogid.",
            ["ServiceAdded"] = "Teenus lisati edukalt!",
            ["ServiceUpdated"] = "Teenus uuendati edukalt!",
            ["ServiceDeleted"] = "Teenus kustutati edukalt!",
            ["ServiceExists"] = "See teenus on juba olemas.",
            ["CannotDeleteService"] = "Seda teenust ei saa kustutada. Eemalda esmalt seotud autoteeninduse logid.",
            ["LogDeleted"] = "Hooldusandmed kustutati edukalt!",
            ["LogExists"] = "Selle kirje jaoks on sellel kuupäeval juba olemas logi.",
            ["InvalidMileage"] = "Lubamatu läbisõidu väärtus.",
            ["InvalidPrice"] = "Palun sisestage kehtiv positiivne hind.",
            ["UpdateOwner"] = "Uuenda omanik",
            ["UpdateCar"] = "Uuenda auto",
            ["UpdateService"] = "Uuenda teenus",
            ["UpdateWorker"] = "Uuenda töötaja",
            ["AddServiceTitle"] = "Lisa teenus",
            ["SelectService"] = "Vali teenus",
            ["AddCarBtn"] = "Lisa auto",
            ["UpdateBtn"] = "Uuenda",
            ["DeleteBtn"] = "Kustuta",
            ["AddServiceBtn"] = "Lisa teenus",
            ["Notifications"] = "Teated",
            ["Logout"] = "Logi välja",
            ["Workers"] = "TÖÖTAJAD",
            ["WorkerName"] = "Töötaja nimi",
            ["WorkerPassword"] = "Töötaja parool",
            ["WorkerRole"] = "Roll",
            ["ManageRoles"] = "Halda rolle",
            ["WorkerAdded"] = "Töötaja lisati edukalt!",
            ["WorkerUpdated"] = "Töötaja uuendati edukalt!",
            ["WorkerDeleted"] = "Töötaja kustutati edukalt!",
            ["CannotModifyDefault"] = "Vaikimisi töötajaid ei saa muuta.",
            ["CannotDeleteDefault"] = "Vaikimisi töötajaid ei saa kustutata.",
            ["Status"] = "Staatus",
            ["ChangeStatus"] = "Muuda staatust",
            ["NotStarted"] = "Alustamata",
            ["InProgress"] = "Pooleli",
            ["Done"] = "Valmis",
            ["AddRole"] = "Lisa roll",
            ["SaveRoles"] = "Salvesta rollid",
            ["CloseRoles"] = "Sulge",
            ["DeleteRole"] = "Kustuta roll",
            ["RolesSavedSuccessfully"] = "Rollid salvestati edukalt!",
            ["CannotDeleteRoleWithWorkers"] = "Ei saa kustutada rolli, millel on määratud töötajaid.",
            ["ViewOwners"] = "Vaata omanikke",
            ["ManageOwners"] = "Halda omanikke",
            ["ViewCars"] = "Vaata autosid",
            ["ManageCars"] = "Halda autosid",
            ["ViewServices"] = "Vaata teenuseid",
            ["ManageServices"] = "Halda teenuseid",
            ["CanChangeStatus"] = "Muuda staatust",
            ["ViewWorkers"] = "Vaata töötajaid",
            ["ManageWorkers"] = "Halda töötajaid",
            ["Hour"] = "Tund",
            ["RoleNameRequired"] = "Rolli nimi on kohustuslik!",
            ["RoleNameMinLength"] = "Rolli nimi peab olema vähemalt 3 tähemärki pikk!",
            ["RoleNameExists"] = "Selle nimega roll on juba olemas!",
            ["RoleMustHavePermission"] = "Rollil peab olema vähemalt üks õigus!",
            ["CannotManageWithoutView"] = "Ei saa hallata ilma vaatamisõiguseta!",
            ["CannotChangeStatusWithoutView"] = "Ei saa staatust muuta ilma autodele või teenustele juurdepääsuta!",
            ["RoleMustHavePermissionFormat"] = "Rollil '{0}' peab olema vähemalt üks õigus!",
            ["CannotManageWithoutViewFormat"] = "Roll '{0}': Ei saa hallata ilma vaatamisõiguseta!",
            ["CannotChangeStatusWithoutViewFormat"] = "Roll '{0}': Ei saa staatust muuta ilma autodele või teenustele juurdepääsuta!",
            ["AssignWorker"] = "Määra töötaja",
        },

        ["RU"] = new()
        {
            ["Title"] = "Автомобильный регистр",
            ["Login"] = "Войти",
            ["Username"] = "Имя пользователя",
            ["Password"] = "Пароль",
            ["Search"] = "Поиск...",
            ["Owners"] = "ВЛАДЕЛЬЦЫ",
            ["Cars"] = "АВТОМОБИЛИ",
            ["ServicesLogs"] = "УСЛУГИ И ЛОГИ",
            ["ID"] = "ID",
            ["Name"] = "Имя",
            ["Phone"] = "Телефон",
            ["Actions"] = "Действия",
            ["AddCar"] = "Добавить авто",
            ["Update"] = "Обновить",
            ["Delete"] = "Удалить",
            ["Add"] = "Добавить",
            ["Brand"] = "Марка",
            ["Model"] = "Модель",
            ["RegNumber"] = "Рег. номер",
            ["Owner"] = "Владелец",
            ["AddService"] = "Добавить услугу",
            ["ServiceName"] = "Название услуги",
            ["Price"] = "Цена",
            ["Car"] = "Авто",
            ["Service"] = "Услуга",
            ["Date"] = "Дата",
            ["Mileage"] = "Пробег",
            ["Save"] = "Сохранить",
            ["Cancel"] = "Отмена",
            ["Message"] = "Сообщение",
            ["OK"] = "ОК",
            ["Welcome"] = "Добро пожаловать, {0}!",
            ["WrongCredentials"] = "Неверное имя пользователя или пароль!",
            ["FillAllFields"] = "Пожалуйста, заполните все поля.",
            ["CarExists"] = "Автомобиль с таким регистрационным номером уже существует.",
            ["CarAdded"] = "Автомобиль успешно добавлен!",
            ["OwnerExists"] = "Этот владелец уже существует.",
            ["OwnerAdded"] = "Владелец успешно добавлен!",
            ["OwnerUpdated"] = "Владелец успешно обновлен!",
            ["OwnerDeleted"] = "Владелец успешно удален.",
            ["CannotDeleteOwner"] = "Невозможно удалить этого владельца. Сначала удалите связанные автомобили.",
            ["CarUpdated"] = "Автомобиль успешно обновлен!",
            ["CarDeleted"] = "Автомобиль успешно удален!",
            ["CannotDeleteCar"] = "Невозможно удалить этот автомобиль. Сначала удалите журналы обслуживания.",
            ["ServiceAdded"] = "Услуга успешно добавлена!",
            ["ServiceUpdated"] = "Услуга успешно обновлена!",
            ["ServiceDeleted"] = "Услуга успешно удалена!",
            ["ServiceExists"] = "Эта услуга уже существует.",
            ["CannotDeleteService"] = "Невозможно удалить эту услугу. Сначала удалите связанные журналы обслуживания.",
            ["LogDeleted"] = "Данные обслуживания успешно удалены!",
            ["LogExists"] = "Запись для этой даты уже существует.",
            ["InvalidMileage"] = "Недопустимое значение пробега.",
            ["InvalidPrice"] = "Пожалуйста, введите действительную положительную цену.",
            ["UpdateOwner"] = "Обновить владельца",
            ["UpdateCar"] = "Обновить автомобиль",
            ["UpdateService"] = "Обновить услугу",
            ["UpdateWorker"] = "Обновить работника",
            ["AddServiceTitle"] = "Добавить услугу",
            ["SelectService"] = "Выберите услугу",
            ["AddCarBtn"] = "Добавить авто",
            ["UpdateBtn"] = "Обновить",
            ["DeleteBtn"] = "Удалить",
            ["AddServiceBtn"] = "Добавить услугу",
            ["Notifications"] = "Уведомления",
            ["Logout"] = "Выйти",
            ["Workers"] = "РАБОТНИКИ",
            ["WorkerName"] = "Имя работника",
            ["WorkerPassword"] = "Пароль работника",
            ["WorkerRole"] = "Роль",
            ["ManageRoles"] = "Управление ролями",
            ["WorkerAdded"] = "Работник успешно добавлен!",
            ["WorkerUpdated"] = "Работник успешно обновлен!",
            ["WorkerDeleted"] = "Работник успешно удален!",
            ["CannotModifyDefault"] = "Невозможно изменить работников по умолчанию.",
            ["CannotDeleteDefault"] = "Невозможно удалить работников по умолчанию.",
            ["Status"] = "Статус",
            ["ChangeStatus"] = "Изменить статус",
            ["NotStarted"] = "Не начато",
            ["InProgress"] = "В процессе",
            ["Done"] = "Готово",
            ["AddRole"] = "Добавить роль",
            ["SaveRoles"] = "Сохранить роли",
            ["CloseRoles"] = "Закрыть",
            ["DeleteRole"] = "Удалить роль",
            ["RolesSavedSuccessfully"] = "Роли успешно сохранены!",
            ["CannotDeleteRoleWithWorkers"] = "Невозможно удалить роль с назначенными работниками.",
            ["ViewOwners"] = "Просмотр владельцев",
            ["ManageOwners"] = "Управление владельцами",
            ["ViewCars"] = "Просмотр автомобилей",
            ["ManageCars"] = "Управление автомобилями",
            ["ViewServices"] = "Просмотр услуг",
            ["ManageServices"] = "Управление услугами",
            ["CanChangeStatus"] = "Изменить статус",
            ["ViewWorkers"] = "Просмотр работников",
            ["ManageWorkers"] = "Управление работниками",
            ["Hour"] = "Час",
            ["RoleNameRequired"] = "Имя роли требуется!",
            ["RoleNameMinLength"] = "Имя роли должно содержать минимум 3 символа!",
            ["RoleNameExists"] = "Роль с этим именем уже существует!",
            ["RoleMustHavePermission"] = "Роль должна иметь хотя бы одно разрешение!",
            ["CannotManageWithoutView"] = "Невозможно управлять без прав просмотра!",
            ["CannotChangeStatusWithoutView"] = "Невозможно изменить статус без доступа к автомобилям или услугам!",
            ["RoleMustHavePermissionFormat"] = "Роль '{0}' должна иметь хотя бы одно разрешение!",
            ["CannotManageWithoutViewFormat"] = "Роль '{0}': Невозможно управлять без прав просмотра!",
            ["CannotChangeStatusWithoutViewFormat"] = "Роль '{0}': Невозможно изменить статус без доступа к автомобилям или услугам!",

            ["AssignWorker"] = "Назначить работника",
        },

        ["UK"] = new()
        {
            ["Title"] = "Car Register",
            ["Login"] = "Login",
            ["Username"] = "Username",
            ["Password"] = "Password",
            ["Search"] = "Search...",
            ["Owners"] = "OWNERS",
            ["Cars"] = "CARS",
            ["ServicesLogs"] = "SERVICES & LOGS",
            ["ID"] = "ID",
            ["Name"] = "Name",
            ["Phone"] = "Phone",
            ["Actions"] = "Actions",
            ["AddCar"] = "Add Car",
            ["Update"] = "Update",
            ["Delete"] = "Delete",
            ["Add"] = "Add",
            ["Brand"] = "Brand",
            ["Model"] = "Model",
            ["RegNumber"] = "Reg Number",
            ["Owner"] = "Owner",
            ["AddService"] = "Add Service",
            ["ServiceName"] = "Service Name",
            ["Price"] = "Price",
            ["Car"] = "Car",
            ["Service"] = "Service",
            ["Date"] = "Date",
            ["Mileage"] = "Mileage",
            ["Save"] = "Save",
            ["Cancel"] = "Cancel",
            ["Message"] = "Message",
            ["OK"] = "OK",
            ["Welcome"] = "Welcome, {0}!",
            ["WrongCredentials"] = "Wrong username or password!",
            ["FillAllFields"] = "Please fill in all fields.",
            ["CarExists"] = "A car with that registration number already exists.",
            ["CarAdded"] = "Car added successfully!",
            ["OwnerExists"] = "This owner already exists.",
            ["OwnerAdded"] = "Owner added successfully!",
            ["OwnerUpdated"] = "Owner updated successfully!",
            ["OwnerDeleted"] = "Owner deleted successfully!",
            ["CannotDeleteOwner"] = "Cannot delete this owner. Remove linked cars first.",
            ["CarUpdated"] = "Car updated successfully!",
            ["CarDeleted"] = "Car deleted successfully!",
            ["CannotDeleteCar"] = "Cannot delete this car until logs are deleted.",
            ["ServiceAdded"] = "Service added successfully!",
            ["ServiceUpdated"] = "Service updated successfully!",
            ["ServiceDeleted"] = "Service deleted successfully!",
            ["ServiceExists"] = "This service already exists.",
            ["CannotDeleteService"] = "Cannot delete this service. Remove related logs first.",
            ["LogDeleted"] = "Log deleted successfully!",
            ["LogExists"] = "A log already exists for this date.",
            ["InvalidMileage"] = "Invalid mileage value.",
            ["InvalidPrice"] = "Please enter a valid positive price.",
            ["UpdateOwner"] = "Update Owner",
            ["UpdateCar"] = "Update Car",
            ["UpdateService"] = "Update Service",
            ["UpdateWorker"] = "Update Worker",
            ["AddServiceTitle"] = "Add Service",
            ["SelectService"] = "Select Service",
            ["AddCarBtn"] = "Add Car",
            ["UpdateBtn"] = "Update",
            ["DeleteBtn"] = "Delete",
            ["AddServiceBtn"] = "Add Service",
            ["Notifications"] = "Notifications",
            ["Logout"] = "Log Out",
            ["Workers"] = "WORKERS",
            ["WorkerName"] = "Worker Name",
            ["WorkerPassword"] = "Worker Password",
            ["WorkerRole"] = "Role",
            ["ManageRoles"] = "Manage Roles",
            ["WorkerAdded"] = "Worker added successfully!",
            ["WorkerUpdated"] = "Worker updated successfully!",
            ["WorkerDeleted"] = "Worker deleted successfully!",
            ["CannotModifyDefault"] = "Cannot modify default workers.",
            ["CannotDeleteDefault"] = "Cannot delete default workers.",
            ["Status"] = "Status",
            ["ChangeStatus"] = "Change Status",
            ["NotStarted"] = "Not Started",
            ["InProgress"] = "In Progress",
            ["Done"] = "Done",
            ["AddRole"] = "Add Role",
            ["SaveRoles"] = "Save Roles",
            ["CloseRoles"] = "Close",
            ["DeleteRole"] = "Delete Role",
            ["RolesSavedSuccessfully"] = "Roles saved successfully!",
            ["CannotDeleteRoleWithWorkers"] = "Cannot delete role with assigned workers.",
            ["ViewOwners"] = "View Owners",
            ["ManageOwners"] = "Manage Owners",
            ["ViewCars"] = "View Cars",
            ["ManageCars"] = "Manage Cars",
            ["ViewServices"] = "View Services",
            ["ManageServices"] = "Manage Services",
            ["CanChangeStatus"] = "Change Status",
            ["ViewWorkers"] = "View Workers",
            ["ManageWorkers"] = "Manage Workers",
            ["Hour"] = "Hour",
            ["RoleNameRequired"] = "Role name is required!",
            ["RoleNameMinLength"] = "Role name must be at least 3 characters long!",
            ["RoleNameExists"] = "A role with this name already exists!",
            ["RoleMustHavePermission"] = "Role must have at least one permission!",
            ["CannotManageWithoutView"] = "Cannot manage without view permission!",
            ["CannotChangeStatusWithoutView"] = "Cannot change status without viewing cars or services!",
            ["RoleMustHavePermissionFormat"] = "Role '{0}' must have at least one permission!",
            ["CannotManageWithoutViewFormat"] = "Role '{0}': Cannot manage without view permission!",
            ["CannotChangeStatusWithoutViewFormat"] = "Role '{0}': Cannot change status without viewing cars or services!",
            ["AssignWorker"] = "Assign Worker",
        }
    };

    public static string CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            _currentLanguage = value;
            SaveLanguage();
        }
    }

    public static string Get(string key)
    {
        if (Translations.ContainsKey(_currentLanguage) &&
            Translations[_currentLanguage].ContainsKey(key))
            return Translations[_currentLanguage][key];
        return key;
    }

    public static string Format(string key, params object[] args)
    {
        string template = Get(key);
        return string.Format(template, args);
    }

    public static void LoadLanguage()
    {
        if (File.Exists(_settingsPath))
            _currentLanguage = File.ReadAllText(_settingsPath).Trim();
    }

    private static void SaveLanguage()
    {
        File.WriteAllText(_settingsPath, _currentLanguage);
    }
}