// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tund9;

#nullable disable

namespace Tund9.Migrations
{
    [DbContext(typeof(TootedContext))]
    partial class TootedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tund9.Kategooria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategooriaNimetus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kirjeldus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategooriad", (string)null);
                });

            modelBuilder.Entity("Tund9.Toode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Hind")
                        .HasColumnType("float");

                    b.Property<int>("KategooriaId")
                        .HasColumnType("int");

                    b.Property<int>("Kogus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Lisatud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pilt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToodeNimetus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategooriaId");

                    b.ToTable("Tooted", (string)null);
                });

            modelBuilder.Entity("Tund9.Toode", b =>
                {
                    b.HasOne("Tund9.Kategooria", "Kategooria")
                        .WithMany("Tooted")
                        .HasForeignKey("KategooriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategooria");
                });

            modelBuilder.Entity("Tund9.Kategooria", b =>
                {
                    b.Navigation("Tooted");
                });
#pragma warning restore 612, 618
        }
    }
}
